name: Build Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Download ffmpeg
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          bun install -g wrangler@latest
          wrangler r2 object get --remote aamrp/binaries/ffmpeg-x86_64-pc-windows-msvc.exe --file ./src-tauri/binaries/ffmpeg-x86_64-pc-windows-msvc.exe
      - run: bun tauri build
      - uses: actions/upload-artifact@v7
        with:
          path: src-tauri/target/release/bundle/*
